[project]
authors = ["Marius Seritan <39998+winding-lines@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "arrow"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "mojo test -I ."
build = "mkdir -p dist && mojo package arrow -o dist/arrow.mojopkg"
clean = "rm -rf dist"
fmt = "mojo format arrow test"

[dependencies]
max = "*"
python = "==3.11"
pyarrow = ">=19.0.1,<20"
pre-commit = ">=4.2.0,<5"
